feat(cmake-workflow): cpack support
These new package option allows overriding the package name and package directory. Custom generators can be set and the results can be uploaded as artifacts.

diff --git a/cmake-workflow/action.yml b/cmake-workflow/action.yml
--- a/cmake-workflow/action.yml
+++ b/cmake-workflow/action.yml
@@ -124,14 +124,57 @@ inputs:
     default: 'true'
 
   # Packaging options
-  # package:
-  #   description: 'Run cpack with the specified generators after the install step.'
-  #   required: false
-  #   default: 'false'
-  # cpack-generators:
-  #   description: 'Generators used by cpack.'
-  #   required: false
-  #   default: ''
+  package:
+    description: |
+      Run cpack with the specified generators after the install step.
+
+    required: false
+    default: 'false'
+
+  package-name:
+    description: |
+      The name of the package (or application). If not specified, it defaults to the project name.
+
+    required: false
+    default: ''
+
+  package-dir:
+    description: |
+      The directory in which the packages are generated by cpack. 
+      
+      If it is not set then this will default to the build dir. 
+      
+      The CPACK_PACKAGE_DIRECTORY may be defined in CMakeLists.txt, a CPack config file or from the cpack command 
+      line option -B. 
+      
+      If set, the command line option overrides the value found in the config file.
+
+    required: false
+    default: ''
+
+  package-vendor:
+    description: |
+      Override/define CPACK_PACKAGE_VENDOR.
+
+    required: false
+    default: ''
+
+  package-generators:
+    description: |
+      A semicolon-separated list of generator names used by cpack.
+      
+      If this variable is not set, the action will attempt to generate the package with all
+      cpack generators available to CMake.
+
+    required: false
+    default: ''
+
+  package-artifact:
+    description: |
+      Whether the packages generated with cpack should be stored as action artifacts.
+
+    required: false
+    default: 'true'
 
   # Annotation options
   create-annotations:
@@ -295,6 +338,16 @@ runs:
         fi
         echo -E "build_dir=$build_dir" >> $GITHUB_OUTPUT
 
+        package_dir="${{ inputs.package-dir }}"
+        if [[ $package_dir == "" ]]; then
+            # package_dir is build_dir itself
+            package_dir="$build_dir"
+        elif [[ $package_dir != /* ]]; then
+            # if relative, package_dir is relative to build_dir 
+            package_dir="$(readlink -f "$build_dir/$package_dir" 2>/dev/null || realpath -e "$build_dir/$package_dir" 2>/dev/null || echo "$build_dir/$package_dir")"
+        fi
+        echo -E "package_dir=$package_dir" >> $GITHUB_OUTPUT
+
     - name: Configure All
       shell: bash
       id: configure
@@ -311,7 +364,7 @@ runs:
             fi
             std_build_dir="${{ steps.params.outputs.build_dir }}$( [ "$cxxstd" == "${{ steps.params.outputs.main_cxxstd }}" ] && echo "" || echo "-$cxxstd" )"
 
-            # Configure step
+            # Build parameters
             CONFIGURE_ARGS=(${{ (steps.setup-cmake.outputs.supports-path-to-build == 'true' && format('"-S" "{0}" "-B" "$std_build_dir"', steps.params.outputs.source_dir)) || '' }})
             CONFIGURE_ARGS+=(${{ (inputs.generator && format('"-G" "{0}"', inputs.generator)) || '' }})
             if [[ "${{ inputs.cxxflags }}" == *"/m32"* ]] && [[ "${{ inputs.generator }}" == "Visual Studio"* ]]; then
@@ -320,32 +373,38 @@ runs:
             CONFIGURE_ARGS+=(${{ (steps.generator.outputs.is_multi_config == 'false' && format('"-D" "CMAKE_BUILD_TYPE={0}"', inputs.build-type || 'Release')) || '' }})
             CONFIGURE_ARGS+=(${{ (steps.generator.outputs.is_multi_config == 'true' && format('"-D" "CMAKE_CONFIGURATION_TYPES={0}"', inputs.build-type || 'Release')) || '' }})
             CONFIGURE_ARGS+=(${{ (inputs.toolchain && format('"-D" "CMAKE_TOOLCHAIN_FILE={0}"', inputs.toolchain)) || '' }})
-            CONFIGURE_ARGS+=(${{ (inputs.install-prefix && format('"-D" "CMAKE_INSTALL_PREFIX={0}"', inputs.install-prefix)) || '' }})
             CONFIGURE_ARGS+=(${{ (inputs.run-tests && '"-D" "BUILD_TESTING=ON"') || '' }})
             CONFIGURE_ARGS+=(${{ (inputs.shared && '"-D" "BUILD_SHARED_LIBS=ON"') || '' }})
             CONFIGURE_ARGS+=(${{ (inputs.cc && format('"-D" "CMAKE_C_COMPILER={0}"', steps.params.outputs.cc)) || '' }})
             CONFIGURE_ARGS+=(${{ (inputs.cxx && format('"-D" "CMAKE_CXX_COMPILER={0}"', steps.params.outputs.cxx)) || '' }})
-            
+        
+            # Install and package parameters
+            CONFIGURE_ARGS+=(${{ (inputs.install-prefix && format('"-D" "CMAKE_INSTALL_PREFIX={0}"', inputs.install-prefix)) || '' }})
+            CONFIGURE_ARGS+=(${{ (inputs.package-generators != '' && format('"-D" "CPACK_GENERATOR={0}"', inputs.package-generators)) || '' }})
+            CONFIGURE_ARGS+=(${{ (inputs.package-name != '' && format('"-D" "CPACK_PACKAGE_NAME={0}"', inputs.package-name)) || '' }})
+            CONFIGURE_ARGS+=(${{ (inputs.package-dir != '' && format('"-D" "CPACK_PACKAGE_DIRECTORY={0}"', steps.params.outputs.package_dir)) || '' }})
+            CONFIGURE_ARGS+=(${{ (inputs.package-vendor != '' && format('"-D" "CPACK_PACKAGE_VENDOR={0}"', inputs.package-vendor)) || '' }})
+        
             ccflags="${{ inputs.ccflags }}"
             ccflags=$(echo "$ccflags" | sed 's/\/m32//g')
             if [ "$ccflags" != "" ]; then
                 CONFIGURE_ARGS+=("-D" "CMAKE_C_FLAGS=$ccflags")
             fi
-            
+        
             cxxflags="${{ inputs.cxxflags }}"
             cxxflags=$(echo "$cxxflags" | sed 's/\/m32//g')
             if [ "$cxxflags" != "" ]; then
                 CONFIGURE_ARGS+=("-D" "CMAKE_CXX_FLAGS=$cxxflags")
             fi
-            
+        
             CONFIGURE_ARGS+=($( [ "$cxxstd" == "defaultcxx" ] && echo "" || echo "-D CMAKE_CXX_STANDARD=$cxxstd" ))
-            SOURCE_DIR_ARG=${{ (steps.setup-cmake.outputs.supports-path-to-build == 'false' && format('{0}', steps.params.outputs.source_dir)) || '' }}
+            SOURCE_DIR_ARG=(${{ (steps.setup-cmake.outputs.supports-path-to-build == 'false' && format('"{0}"', steps.params.outputs.source_dir)) || '' }})
         
             mkdir "$std_build_dir" || true
             cd "$std_build_dir"
             set +e
             set -x
-            "${{ steps.params.outputs.cmake_path }}" "${CONFIGURE_ARGS[@]}" ${{ inputs.extra-args }} $SOURCE_DIR_ARG 2>&1 | tee -a "$std_build_dir/cmake-configure-output.txt"
+            "${{ steps.params.outputs.cmake_path }}" "${CONFIGURE_ARGS[@]}" ${{ inputs.extra-args }} "${SOURCE_DIR_ARG[@]}" 2>&1 | tee -a "$std_build_dir/cmake-configure-output.txt"
             exit_code=$?
             if [[ $exit_code -ne 0 ]]; then
               break
@@ -355,7 +414,7 @@ runs:
             cd "${{ steps.params.outputs.source_dir }}"
         done
         echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
-        
+
     - name: Configure All (Annotations)
       if: ${{ inputs.create-annotations == 'true' }}
       shell: bash
@@ -431,7 +490,7 @@ runs:
               false
             fi        
         done
-    
+
     - name: Build All
       shell: bash
       id: build
@@ -550,7 +609,7 @@ runs:
               false
             fi
         done
-    
+
     - name: Test
       shell: bash
       id: test
@@ -632,7 +691,7 @@ runs:
             fi        
         done
 
-    - name: Install All
+    - name: Install main cxxstd
       shell: bash
       if: ${{ inputs.install == 'true' }}
       working-directory: ${{ inputs.source_dir }}
@@ -665,3 +724,167 @@ runs:
               fi
             fi
         done
+
+    - name: Package main cxxstd
+      shell: bash
+      id: cpack
+      if: ${{ inputs.package == 'true' }}
+      run: |
+        # Package ${{ steps.params.outputs.main_cxxstd }}
+        ${{ (inputs.trace-commands == 'true' && 'set -xe') || '' }}
+        
+        working_dir=$(pwd)
+        
+        std_build_dir="${{ steps.params.outputs.build_dir }}"
+        cd "$std_build_dir"
+        
+        # determine default generator
+        generators="${{ inputs.package-generators }}"
+        fail_is_ok=false
+        if [ "$generators" == "" ]; then
+          generators=$(cpack --help | awk '/Generators/ {flag=1; next} flag && NF {print $1}' ORS=';' | sed 's/;$//')
+          # failure is OK when we try all default generators as the requirements for all default generators are
+          # rarely available
+          fail_is_ok=true
+        fi
+        
+        # cpack arguments
+        std_build_dir="${{ steps.params.outputs.build_dir }}"
+        output=""
+        touch "$std_build_dir/cpack-output.txt"
+        for generator in ${generators//;/ }
+        do
+          CPACK_ARGS=("-G" "$generator")
+          CPACK_ARGS+=("-C" "${{ inputs.build-type || 'Release' }}")
+          CPACK_ARGS+=(${{ (inputs.trace-commands != '' && '"--verbose"') || '' }})
+          CPACK_ARGS+=(${{ (inputs.package-name != '' && format('"-P" "{0}"', inputs.package-name)) || '' }})
+          CPACK_ARGS+=(${{ (inputs.package-dir != '' && format('"-B" "{0}"', steps.params.outputs.package_dir)) || '' }})
+          CPACK_ARGS+=(${{ (inputs.package-vendor != '' && format('"--vendor" "{0}"', inputs.package-vendor)) || '' }})
+        
+          # run cpack
+          if [ "$fail_is_ok" == "true" ]; then
+              set +e
+          fi
+          "${{ steps.params.outputs.cpack_path }}" "${CPACK_ARGS[@]}" 2>&1 | tee -a "$std_build_dir/cpack-output.txt"
+          if [ "$fail_is_ok" == "true" ]; then
+              set -e
+          fi
+        done
+        
+        # parse output to find package files
+        output=$(cat "$std_build_dir/cpack-output.txt")
+        package_lines=$(echo "$output" | grep 'CPack: - package:')
+        paths=()
+        while IFS= read -r line; do
+          path=$(echo "$line" | sed -n 's/CPack: - package: \(.*\) generated\./\1/p')
+          if [ -f "$path" ]; then
+            paths+=("$path")
+          fi
+        done <<< "$package_lines"
+        
+        # Aggregate package paths for artifact
+        echo "Package paths:"
+        for path in "${paths[@]}"; do
+          echo "- $path"
+        done
+        
+        # Determine artifact pattern
+        common_prefix="${paths[0]}"
+        for path in "${paths[@]}"; do
+          echo "path=$path"
+          while [[ "$path" != "$common_prefix"* ]]; do
+            common_prefix="${common_prefix%?}"
+            echo "common_prefix=$common_prefix"
+          done
+        done
+
+        artifact_pattern=$(basename "$common_prefix")
+        echo "artifact_pattern=$artifact_pattern*" >> $GITHUB_OUTPUT
+
+        # Clean intermediary package artifacts
+        package_dir=$(dirname "$common_prefix")
+        if [ -d "$package_dir/_CPack_Packages" ]; then
+          rm -rf "$package_dir/_CPack_Packages"
+        fi
+
+        # Calculate package_dir relative to default actions working path
+        relative_package_dir="$(realpath --relative-to="$working_dir" "$package_dir" 2>/dev/null || echo "$package_dir")"
+        if [[ "$relative_package_dir" == $working_dir* ]]; then
+          relative_package_dir="${package_dir#$working_dir}"
+          relative_package_dir="${relative_package_dir#/}"
+        fi
+        echo -E "relative_package_dir=$relative_package_dir" >> $GITHUB_OUTPUT
+
+        # Define artifact name for the packages
+        artifact_name=${{ runner.os }}
+        artifact_name="$(echo "$artifact_name" | tr '[:upper:]' '[:lower:]')"
+        
+        # Determine ubuntu version if ubuntu
+        if [ "$artifact_name" == "linux" ]; then
+          ubuntu_version=""
+          set +e
+          if [ "$ubuntu_version" == "" ]; then
+            ubuntu_version=$(lsb_release -rs)
+          fi
+          
+          if [ "$ubuntu_version" == "" ]; then
+            # Extract Ubuntu version from /etc/os-release
+            os_release=$(cat /etc/os-release)
+            version_regex='VERSION_ID="([^"]+)"'
+            if [[ $os_release =~ $version_regex ]]; then
+              ubuntu_version=${BASH_REMATCH[1]}
+            else
+              ubuntu_version=""
+            fi
+          fi
+          
+          if [ "$ubuntu_version" == "" ]; then
+            # Extract Ubuntu version from /etc/lsb-release
+            lsb_release=$(cat /etc/lsb-release)
+            version_regex='DISTRIB_RELEASE=([^ ]+)$'
+            if [[ $lsb_release =~ $version_regex ]]; then
+              ubuntu_version=${BASH_REMATCH[1]}
+            fi
+          fi
+          
+          if [ "$ubuntu_version" == "" ]; then
+            # Extract Ubuntu version from uname -a
+            uname_output=$(uname -a)
+            version_regex='~([0-9]+\.[0-9]+)'
+            if [[ $uname_output =~ $version_regex ]]; then
+              ubuntu_version=${BASH_REMATCH[1]}
+            fi
+          fi
+        
+          if [ "$ubuntu_version" != "" ]; then
+            artifact_name+="-ubuntu-$ubuntu_version"
+          fi
+          set -e
+        fi
+          
+        cxx="${{ inputs.cxx }}"
+        if [ "$cxx" == "" ] && [ "$artifact_name" == "windows" ]; then
+          artifact_name+="-msvc"
+        elif [ "$cxx" != "" ]; then
+          cxx=$(basename "$cxx" | cut -d. -f1)
+          if [[ "$cxx" == "clang++"* ]]; then
+            cxx="${cxx/clang++/clang}"
+          elif [[ "$cxx" == "g++"* ]]; then
+            cxx="${cxx/g++/gcc}"
+          fi
+          if [[ "$cxx" == "gcc"* ]] && [[ "$artifact_name" == "windows" ]]; then
+            cxx="${cxx/gcc/mingw}"
+          fi
+          artifact_name+="-$cxx"
+        fi
+      
+        artifact_name+="-packages"
+        echo "artifact_name=$artifact_name" >> $GITHUB_OUTPUT
+        echo "Artifact name: $artifact_name"
+
+    - uses: actions/upload-artifact@v3
+      if: ${{ inputs.package == 'true' && inputs.package-artifact == 'true' }}
+      with:
+        name: ${{ steps.cpack.outputs.artifact_name }}
+        path: |
+          ${{ steps.cpack.outputs.relative_package_dir }}/${{ steps.cpack.outputs.artifact_pattern }}
